encoder:
  name: bert-base-nli-mean-tokens
  data_filter:
    name: tf-idf
    params:
      number_of_words: 10
  dataset_dir:  ${JOBXMLC_DATA}/dataset
  embeddings_save_dir : ${JOBXMLC_DATA}/embeddings