encoder:
  name: fasttext
  params:
    model_path: ../data/COLING/Fine-FTCondensedData/fine-tune-FTskill.bin
  data_filter:
    name: tf-idf
    params:
      number_of_words: 10
  dataset_dir:  ${JOBXMLC_DATA}/dataset
  embeddings_save_dir : ${JOBXMLC_DATA}/embeddings